### ISSUE TITLE
Full guide from zero please

### ISSUE THREAD

**Issue by himawanwi** [goodthebest/yiimp#1]
Full guide from zero pleasev

**Comment by goodthebest** [comment]
As much as technical details need, they are already available on the git page, https://github.com/goodthebest/yiimp

 if you need more personalized service you can hire me and I'll install it on your server to setup pool.

**Comment by himawanwi** [comment]
please share me your discord

**Comment by goodthebest** [comment]
You can add me in Skype this email:
onlinebuybiz@gmail.com

**Comment by goodthebest** [comment]
in Discord you can also add me

@goodthebest7#6606
