### ISSUE TITLE
This repository not compiling on ARM processor

### ISSUE THREAD

**Issue by Master-01** [goodthebest/yiimp#2]
Hellow!
My system Linux OrangePiPC 3.4.113-sun8i #18 SMP PREEMPT Wed Jan 24 22:10:49 CET 2018 armv7l armv7l armv7l GNU/Linux
I download https://github.com/goodthebest/yiimp.git
I installed nginx, mysql, memcache, php
I enter into dir: yiimp/stratum
and call make command 
getting error:
...
gcc -g -march=native -DNO_EXCHANGE -DHAVE_CURL `mysql_config --cflags --libs` -c stratum.cpp
gcc -g -march=native -DNO_EXCHANGE -DHAVE_CURL `mysql_config --cflags --libs` -c db.cpp
gcc -g -march=native -DNO_EXCHANGE -DHAVE_CURL `mysql_config --cflags --libs` -c coind.cpp
gcc -g -march=native -DNO_EXCHANGE -DHAVE_CURL `mysql_config --cflags --libs` -c coind_aux.cpp
gcc -g -march=native -DNO_EXCHANGE -DHAVE_CURL `mysql_config --cflags --libs` -c coind_template.cpp
/tmp/ccEw1zER.s: Assembler messages:
/tmp/ccEw1zER.s:132: Error: bad instruction `bswapl r3'
Makefile:49: recipe for target 'coind_template.o' failed
make: *** [coind_template.o] Error 1

You said that you can help me. Please help - how to compile and use the current pool?

**Comment by goodthebest** [comment]
You should try on OS, Ubuntu 16.04.03 or 16.04.04

**Comment by Master-01** [comment]
OK.
Im cloned this respository into another system: **Linux ad028 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux**
and I  enter into dir yiimp/stratum and make command
_gcc stratum.o db.o coind.o coind_aux.o coind_template.o coind_submit.o util.o list.o rpc.o job.o job_send.o job_core.o merkle.o share.o socket.o coinbase.o client.o client_submit.o client_core.o client_difficulty.o remote.o remote_template.o user.o object.o json.o base58.o rpc_curl.o iniparser/libiniparser.a algos/libalgos.a sha3/libhash.a -lpthread -lgmp -lm -lstdc++ -lmysqlclient -O2 `mysql_config --libs` -L/usr/lib/x86_64-linux-gnu/mit-krb5 -lcurl -lidn -lrtmp -lssl -lcrypto -lssl -lcrypto -Wl,-Bsymbolic-functions -Wl,-z,relro -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -llber -lldap -lz -o stratum
/usr/bin/ld: cannot find -lrtmp
/usr/bin/ld: cannot find -lgssapi_krb5
/usr/bin/ld: cannot find -lkrb5
/usr/bin/ld: cannot find -lk5crypto
/usr/bin/ld: cannot find -lcom_err
collect2: error: ld returned 1 exit status
Makefile:46: recipe for target 'stratum' failed
make: *** [stratum] Error 1_

how install -lrtmp and another packages into system ubuntu 16?

**Comment by goodthebest** [comment]
install these dependencies

sudo apt-get -y install libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils git cmake libboost-all-dev zlib1g-dev libz-dev libseccomp-dev libcap-dev libminiupnpc-dev

**Comment by goodthebest** [comment]
most probably it's lack of all dependencies.  

If you want I can install it for a fee, you can get in touch with me if interested.

**Comment by Master-01** [comment]
that is, you yourself do not know what's the matter? This is bad.

**Comment by goodthebest** [comment]
Well as I said it's dependencies issue. Since you cannot figure that out in your machine then it's hard to help you unless some expert take care of it.
